before_install:
  - gem install sass
language: node_js
node_js:
  - "0.11"
before_script:
  - npm install grunt-cli -g
script:
  - grunt
deploy:
  provider: s3
  access_key_id: "AKIAIRN4SGW2YI7AQMEA"
  secret_access_key: "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"
  bucket: "bethelmedia"
  skip_cleanup: true
  local_dir: src
notifications:
  slack: zacharnold:1q8bdkXpx44bogOGyVM5gokt